language: csharp
mono: none
dotnet: 2.2
dist: trusty
sudo: required

install:
 - dotnet restore

script:
 - dotnet build --configuration Release

deploy:
  provider: azure_web_apps
  verbose: true
  skip_cleanup: true