language: csharp
mono: none
dotnet: 2.2
dist: xenial
sudo: required

git:
   depth: false

script:
 - dotnet restore
 - dotnet build --configuration Release

deploy:
  provider: azure_web_apps
  verbose: true
  skip_cleanup: true